spring:
  application:
    name: lottery-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lottery_system?characterEncoding=utf8&useSSL=false
    username: root
    password: "045511"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 8888
      timeout: 60s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s
  web:
    resources:
      static-locations: classpath:/static/,file:${pic.local-path}/
  rabbitmq:
    host: 101.43.87.239
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 5
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 1771469353@qq.com
    password:
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-handlers-package: com.example.lotterysystem.dao.handler
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml

sms:
  access-key-id:
  access-key-secret:
  sign-name: 速通互联验证码

pic:
  local-path: D:/PIC

async:
  executor:
    thread:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 20
      name:
        prefix: async-service-